import { ReduxProvider } from './redux-provider';
import { Providers } from './providers';
import '@/styles/globals.css';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
				<html lang='es-MX'>
					<body>
						<ReduxProvider>
							<Providers>{children}</Providers>
						</ReduxProvider>
					</body>
				</html>
	);
}
